--Create table Login
--(
-- RID bigint Primary Key identity(1,1),
-- Name nvarchar(max) null,
-- FatherName nvarchar(max) null,
-- EmailID nvarchar(max) null,
-- MobileNumber bigint not null default(0),
-- Address nvarchar(max),
-- Password nvarchar(max),
-- UserName nvarchar(max)
--)

